/**
 * Author: Huy Dang
 * Date: 03/02/2010
 * 
 * Simple database access helper class. The Database contains all
 * valid bus numbers which are in Seattle area. This database is used to 
 * validate the input.
 */
package com.busstopalarm;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import android.content.Context;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class BusNumDbAdapter {
	
	private final Context mCtx;
    private DatabaseHelper mDbHelper;
    private SQLiteDatabase mDb;
	
	/*
	 * bus_num TABLE KEYS
     * _id: the id is generated by system to keep track of entry (Primary key)
     * route_id: the bus route id
	 */
    private static final String DATABASE_TABLE_DEST = "bus_num";
    private static final String TAG = "BusNumDbAdapter";
    private static final String DATABASE_NAME = "data";
    private static final int DATABASE_VERSION = 2;
	
    /**
     * Database Query Statements
     */
    private static final String DATABASE_CREATE_DEST=
            "CREATE TABLE "
            + " bus_num (_id INTEGER PRIMARY KEY AUTOINCREMENT, "
            + " route_id TEXT NOT NULL );";

    private static final String DATABASE_INSERT_DEST =
    		" INSERT INTO bus_num (route_id) VALUES (?);";	
    	
    private static final String DATABASE_RETRIEVE_BY_ROUTEID =
    		" SELECT * FROM bus_num WHERE route_id = ?;";
    
    private static final String DATABASE_RETRIEVE_BY_ROWID =
    		" SELECT * FROM bus_num WHERE _id = ? ;";
          	
    private static final String DATABASE_FETCH_ALL_BUS =
    		" SELECT * FROM bus_num ;";
        
    private static final String DATABASE_FETCH_ALL_BUS_LIMIT =
			" SELECT * FROM bus_num LIMIT ?  ;";

    /**
     * Private class DatabaseHelper is used for create/initialize the table
     * at the begin and help to update to new version
     */
    private static class DatabaseHelper extends SQLiteOpenHelper {

        DatabaseHelper(Context context) {
            super(context, DATABASE_NAME, null, DATABASE_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
        	db.execSQL(DATABASE_CREATE_DEST);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, 
        					  int oldVersion, int newVersion) {
            Log.w(TAG, "Upgrading database from version " + oldVersion + " to "
                    + newVersion + ", which will destroy all old data");
            db.execSQL("DROP TABLE IF EXISTS bus_num ");
            onCreate(db);
        }
    }

    /**
     * Constructor - takes the context to allow the database to be
     * opened/created
     * 
     * @param ctx the Context within which to work
     */
    public BusNumDbAdapter(Context ctx) {
        this.mCtx = ctx;
    }

    /**
     * Opens the data database. If it cannot be opened, try to create a 
     * new instance of the database. If it cannot be created, throw an exception 
     * to signal the failure
     * 
     * @return this (self reference, allowing this to be chained in an
     *         initialization call)
     * @throws SQLException if the database could be neither opened or created
     */
    public BusNumDbAdapter open() throws SQLException {
        mDbHelper = new DatabaseHelper(mCtx);
        mDb = mDbHelper.getWritableDatabase();
        return this;
    }
    
    /**
     * Closes the bus_num database. If there's no current database running,
     * simply do nothing
     */
    public void close() {
        mDbHelper.close();
    }

    /**
     * Deletes all bus entries from the bus_num table
     * 
     * @return true if all bus entries deleted, false otherwise
     */
    public boolean deleteAllBusEntries() {
        return mDb.delete(DATABASE_TABLE_DEST, null, null) > 0;
    }

    /**
     * Creates a new entry using the route_id. This is private function to 
     * initialize bus_num table by reading well formatted text file.
     */
    private void createBusEntry(String route_id) {
    	 	
    	String[] args = {route_id};
    	mDb.rawQuery(DATABASE_INSERT_DEST, args);
    }
   
    /**
     * Returns a cursor over the list of all entries in bus_num table
     * 
     * @return Cursor over all bus entries
     */
    public Cursor fetchAllBusEntries() {
    	return mDb.rawQuery(DATABASE_FETCH_ALL_BUS, new String[]{});
    }
    
    /**
     * Returns the number of rows in the current bus_num table
     * 
     * @return number of rows in the bus_num table
     */
    public int getBusNumTbSize() {
    	Cursor mCursor = mDb.rawQuery(DATABASE_FETCH_ALL_BUS, new String[]{});
    	return mCursor.getCount();
    }
  
   /**
    * Checks if a entry is already in the database based on route_id
    * 
    * @param route_id Id of the bus route
    * @return true if the entry is already in the table. false otherwise.
    */
   	public boolean checkIfBusEntryExist(String route_id) {
   		Cursor mCursor = null;
   		mCursor = mDb.rawQuery(DATABASE_RETRIEVE_BY_ROUTEID, 
   							   new String[]{route_id});

   		if (mCursor.getCount() != 0) {
               return true;
   		}
   		
        return false;
   	}
   	   	
   	/**
   	 * Private function to return specific number of bus entries.
   	 * Using those wrapper classes above instead.
   	 * 
   	 * @param limit number of entries to return
   	 * @return the Cursor of the list of returned entries
   	 */
   	public Cursor getListBusNum(int limit) {
   		Cursor mCursor = mDb.rawQuery(DATABASE_FETCH_ALL_BUS_LIMIT, 
   							          new String[]{Integer.toString(limit)});
   		
   		if (mCursor != null) {
            mCursor.moveToFirst();
        }
        return mCursor;
   	}
   	
   	/**
   	 * Reads the text file in /res/raw/ folder to create the new database for
   	 * bus route number. This is used to validate bus input.
   	 
   	 * @param testFlag reads kingcounty file if the flag value is 0
   	 * 				   reads soundtransit file if the the flag value is 1
   	 * 				   
   	 * @return True if reading the file and put new entries to 
   	 * 		   database successfully. False if not reading the file at all.
   	 */
   	public boolean readDbFile(int testFlag) throws IOException, 
   												   FileNotFoundException {
   		
   		InputStream in=null;
   		if (testFlag == 0) {
   			in = mCtx.getResources().openRawResource(R.raw.kingcounty);
   		} else if (testFlag == 1) {
   			in = mCtx.getResources().openRawResource(R.raw.soundtransit);
   		} 
   		
  		BufferedReader bin = new BufferedReader(new InputStreamReader(in));
  		if (bin == null) {
  			return false;
  		}
  		
  		String line;
  		String result;
  		while (true) {
    		line = bin.readLine();
  			if (line == null) {
  				break;
  			}
  			
    		result = line.toString();
    		Log.v("BusNumDbAdapter 1st", result);
    		createBusEntry(result);
    	}
  		bin.close();
  		return true;
   	}

}
